In [56]:
import pandas as pd

In [57]:
df = pd.read_csv('/content/drive/MyDrive/Internship/student_performance.csv')
display(df.head())

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [58]:
print("shape:",df.shape)

shape: (30, 13)

In [59]:
print("student:",df.shape)

student: (30, 13)

In [60]:
print(df.values.tolist())

[[1001, 'Aarav Sharma', 19, 'Male', 'Computer Science', 2, 85, 78, 72, 91, 92, 'Mumbai', 2023], [1002, 'Priya Patel', 20, 'Female', 'Computer Science', 2, 76, 82, 88, 79, 87, 'Ahmedabad', 2023], [1003, 'Rohit Verma', 19, 'Male', 'Electronics', 2, 65, 74, 61, 55, 78, 'Delhi', 2023], [1004, 'Sneha Reddy', 20, 'Female', 'Mechanical', 2, 70, 80, 75, 48, 95, 'Hyderabad', 2023], [1005, 'Arjun Nair', 19, 'Male', 'Computer Science', 2, 92, 88, 81, 95, 90, 'Kochi', 2023], [1006, 'Meera Joshi', 20, 'Female', 'Electronics', 2, 58, 66, 70, 52, 72, 'Pune', 2023], [1007, 'Kiran Kumar', 21, 'Male', 'Civil', 2, 73, 69, 65, 40, 85, 'Bangalore', 2023], [1008, 'Divya Singh', 19, 'Female', 'Computer Science', 2, 88, 91, 84, 93, 96, 'Lucknow', 2023], [1009, 'Rahul Mishra', 20, 'Male', 'Mechanical', 2, 62, 71, 58, 45, 68, 'Varanasi', 2023], [1010, 'Ananya Das', 19, 'Female', 'Computer Science', 2, 95, 89, 90, 97, 98, 'Kolkata', 2023], [1011, 'Vikram Iyer', 20, 'Male', 'Electronics', 2, 80, 75, 68, 72, 83, 'Chennai', 2023], [1012, 'Pooja Gupta', 19, 'Female', 'Civil', 2, 67, 72, 79, 44, 80, 'Jaipur', 2023], [1013, 'Suresh Rao', 21, 'Male', 'Computer Science', 2, 83, 86, 77, 88, 88, 'Mysore', 2023], [1014, 'Kavya Nambiar', 20, 'Female', 'Mechanical', 2, 74, 78, 82, 51, 91, 'Thrissur', 2023], [1015, 'Ajay Tiwari', 19, 'Male', 'Computer Science', 2, 71, 69, 64, 76, 75, 'Bhopal', 2023], [1016, 'Ritu Agarwal', 20, 'Female', 'Electronics', 2, 87, 83, 86, 69, 93, 'Agra', 2023], [1017, 'Manoj Pandey', 21, 'Male', 'Civil', 2, 56, 61, 55, 38, 65, 'Patna', 2023], [1018, 'Swati Kulkarni', 19, 'Female', 'Computer Science', 2, 90, 87, 85, 92, 94, 'Nagpur', 2023], [1019, 'Deepak Chauhan', 20, 'Male', 'Mechanical', 2, 68, 73, 62, 49, 77, 'Dehradun', 2023], [1020, 'Nisha Kapoor', 19, 'Female', 'Computer Science', 2, 79, 84, 81, 83, 89, 'Chandigarh', 2023], [1021, 'Harish Pillai', 20, 'Male', 'Electronics', 2, 64, 70, 67, 58, 74, 'Thiruvananthapuram', 2023], [1022, 'Tanvi Mehta', 19, 'Female', 'Computer Science', 2, 93, 90, 88, 96, 97, 'Surat', 2023], [1023, 'Sanjay Dubey', 21, 'Male', 'Civil', 2, 61, 66, 59, 42, 70, 'Allahabad', 2023], [1024, 'Preeti Saxena', 20, 'Female', 'Mechanical', 2, 77, 81, 76, 53, 86, 'Kanpur', 2023], [1025, 'Amit Bose', 19, 'Male', 'Computer Science', 2, 86, 82, 79, 89, 91, 'Kolkata', 2023], [1026, 'Rekha Nair', 20, 'Female', 'Electronics', 2, 72, 77, 73, 63, 82, 'Kochi', 2023], [1027, 'Gaurav Shukla', 21, 'Male', 'Computer Science', 2, 84, 79, 75, 87, 87, 'Lucknow', 2023], [1028, 'Sunita Pillai', 19, 'Female', 'Civil', 2, 60, 65, 68, 39, 73, 'Thiruvananthapuram', 2023], [1029, 'Nitin Jain', 20, 'Male', 'Mechanical', 2, 75, 76, 70, 50, 84, 'Indore', 2023], [1030, 'Akanksha Yadav', 19, 'Female', 'Computer Science', 2, 91, 93, 87, 94, 95, 'Agra', 2023]]

In [61]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [62]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [63]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [64]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [65]:
import random

random_row_indices = df.sample(n=5, random_state=42).index
column_names = df.columns.tolist()

for row_index in random_row_indices:
    random_column = random.choice(column_names)
    df.loc[row_index, random_column] = 0

print("DataFrame after setting 5 new random fields to 0:")
display(df)

DataFrame after setting 5 new random fields to 0:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,0,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
15,1016,0,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023
17,0,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023
23,0,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,0,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [66]:
df.isnull()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False

In [67]:
print("Null values after the operation:")
df.isnull().sum()

Null values after the operation:

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [68]:
import numpy as np

df_math_nans = df.copy()

random_row_indices_math_nan = df_math_nans.sample(n=5, random_state=42).index

for row_index in random_row_indices_math_nan:
    df_math_nans.loc[row_index, 'math_score'] = np.nan

print("DataFrame after setting 5 random fields in 'math_score' to `np.nan`:")
display(df_math_nans)

DataFrame after setting 5 random fields in 'math_score' to `np.nan`:

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85.0,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76.0,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65.0,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70.0,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92.0,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58.0,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73.0,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88.0,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,NaN,0,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95.0,89,90,97,98,Kolkata,2023
10,1011,Vikram Iyer,20,Male,Electronics,2,80.0,75,68,72,83,Chennai,2023
11,1012,Pooja Gupta,19,Female,Civil,2,67.0,72,79,44,80,Jaipur,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83.0,86,77,88,88,Mysore,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74.0,78,82,51,91,Thrissur,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71.0,69,64,76,75,Bhopal,2023
15,1016,0,20,Female,Electronics,2,NaN,83,86,69,93,Agra,2023
16,1017,Manoj Pandey,21,Male,Civil,2,56.0,61,55,38,65,Patna,2023
17,0,Swati Kulkarni,19,Female,Computer Science,2,NaN,87,85,92,94,Nagpur,2023
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68.0,73,62,49,77,Dehradun,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79.0,84,81,83,89,Chandigarh,2023
20,1021,Harish Pillai,20,Male,Electronics,2,64.0,70,67,58,74,Thiruvananthapuram,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93.0,90,88,96,97,Surat,2023
22,1023,Sanjay Dubey,21,Male,Civil,2,61.0,66,59,42,70,Allahabad,2023
23,0,Preeti Saxena,20,Female,Mechanical,2,NaN,81,76,53,86,Kanpur,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86.0,82,79,89,91,Kolkata,2023
25,1026,Rekha Nair,20,Female,Electronics,2,72.0,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84.0,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,0,Female,Civil,2,NaN,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75.0,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91.0,93,87,94,95,Agra,2023

In [69]:
df_math_nans.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               5
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [70]:
df = pd.read_csv('/content/drive/MyDrive/Internship/student_performance.csv')
print("DataFrame has been fully reverted to its original state.")
display(df.head())

DataFrame has been fully reverted to its original state.

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [71]:
print(df["department"].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [72]:
print(df["department"].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [73]:
print(df["city"].value_counts())

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [74]:
print(df["gender"].value_counts())

gender
Male      15
Female    15
Name: count, dtype: int64

In [75]:
print(df["gender"].value_counts().sum())

30

In [79]:
cms = df[(df['city']=='Chennai')|(df['city']== 'Mumbai')]
display(cms[['name', 'city', 'programming_score']])

            name     city  programming_score
0   Aarav Sharma   Mumbai                 91
10   Vikram Iyer  Chennai                 72

In [81]:
high_attendance = df[df['attendance_percentage']>=75]
print(f"Number of students with high percentage:{len(low_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Number of students with high percentage:7
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
1      Priya Patel  Computer Science                     87
2      Rohit Verma       Electronics                     78
3      Sneha Reddy        Mechanical                     95
4       Arjun Nair  Computer Science                     90
6      Kiran Kumar             Civil                     85
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
10     Vikram Iyer       Electronics                     83
11     Pooja Gupta             Civil                     80
12      Suresh Rao  Computer Science                     88
13   Kavya Nambiar        Mechanical                     91
14     Ajay Tiwari  Computer Science                     75
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
18  Deepak Chauhan        Mechanical                     77
19    Nisha Kapoor  Computer Science                     89
21     Tanvi Mehta  Computer Science                     97
23   Preeti Saxena        Mechanical                     86
24       Amit Bose  Computer Science                     91
25      Rekha Nair       Electronics                     82
26   Gaurav Shukla  Computer Science                     87
28      Nitin Jain        Mechanical                     84
29  Akanksha Yadav  Computer Science                     95

In [80]:
low_attendance = df[df['attendance_percentage']<=75]
print(f"Number of students with low percentage:{len(low_attendance)}")
print(low_attendance[['name','department','attendance_percentage']])

Number of students with low percentage:7
             name        department  attendance_percentage
5     Meera Joshi       Electronics                     72
8    Rahul Mishra        Mechanical                     68
14    Ajay Tiwari  Computer Science                     75
16   Manoj Pandey             Civil                     65
20  Harish Pillai       Electronics                     74
22   Sanjay Dubey             Civil                     70
27  Sunita Pillai             Civil                     73

In [85]:
t_s = df.loc[df['programming_score'].idxmax()]
b_s = df.loc[df['programming_score'].idxmin()]
display(t_s[['name', 'department', 'programming_score', 'city']].to_frame().T)
display(b_s[['name', 'department', 'programming_score', 'city']].to_frame().T)

         name        department programming_score     city
9  Ananya Das  Computer Science                97  Kolkata

            name department programming_score   city
16  Manoj Pandey      Civil                38  Patna